# Generated by Django 2.0.7 on 2018-12-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('Police_code', models.CharField(max_length=50)),
                ('Group_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
